### ISSUE TITLE
Basic gameplay implementation

### ISSUE THREAD

**Issue by xen-000** [Source2ZE/ZombieReborn#5]
Some basic gameplay mechanics that we need to get out of the way before doing anything else:

### Infection System
- [x] Move everyone to CTs on round start.
- [x] Add a countdown with a minimum and maximum time for initial infection.
- [x] Add human to zombie ratio configuration.
- [x] Keep track of all initially infected zombies (AKA mother zombies).
- [x] Infect anyone who spawns in after mother zombies are selected, this includes people switching teams, so probably best to hook `player_spawn` for that.
### Gameplay
- [x] Setup a rudimentary repeatkiller system that disables zombie respawning in order to end the round.
- [x] Give proper kill credit to zombies who infect humans (maybe see how ze_collective does it)
- [x] #38
- [x] Figure out a way to keep *killed* humans in place while infecting them (like when a zombie right-click knifes them from behind).
### Knockback
- [ ] Setup hitgroups for every player attachment.
- [ ] Setup knockback scaling depending on the weapon used and the human's class.
### Classes
- [x] Mother zombie class.
- [x] Human class.
- [x] Zombie class.

**Comment by Hichatu** [comment]
Basic gameplay is now implemented, knockback hitgroups and scaling is not too important for now.
