### ISSUE TITLE
If !hide doesn't work yet how about replacing it with player size? :)

### ISSUE THREAD

**Issue by eminem0091** [Source2ZE/ZombieReborn#91]
Hello, is it possible to create a feature for player size in zombie reborn? Like in this video - below. It really helps with gameplay visibility (players look like kids, but for gameplay visibility it works).

Thank you.

em

https://youtu.be/LCt1IjzNdSU?t=76

**Comment by Vauff** [comment]
[Already exists](https://github.com/Source2ZE/ZombieReborn/blob/0787a211ac783e94cdf1959980530bfbc25172b1/cfg/zr/playerclass.cfg#L50) since the ZR scripts were originally made. It's available in the new C++ ZR too.
